### ISSUE TITLE
What about other versions

### ISSUE THREAD

**Issue by ghost** [Tarik02/mcpe-patch#2]
What we should do for other versions?

**Comment by tarik02** [comment]
@naja82, I didn't check it. What's wrong with them?

**Comment by ghost** [comment]
Nothing, I don't tested it for other versions.
Do you tested?

**Comment by tarik02** [comment]
@naja82, nope. I don't play mcpe anymore. If you notice some problems with this, you should take some hash from mcpelauncher-linux and put it to patched java file (I don't remember where's it and what's it's name.
